# Generated by Django 3.0.7 on 2020-06-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='techUsed',
            field=models.TextField(),
        ),
    ]
