# Generated by Django 3.0.7 on 2020-06-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0002_auto_20200614_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='link',
            field=models.URLField(default='#'),
            preserve_default=False,
        ),
    ]
