# Generated by Django 3.0.7 on 2020-06-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0004_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='marksheet',
            field=models.URLField(blank=True, null=True),
        ),
    ]
