# Generated by Django 3.0.7 on 2020-06-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0005_auto_20200614_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='board',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
