# Generated by Django 3.0.7 on 2020-06-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0006_education_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField()),
                ('text', models.TextField()),
                ('img', models.URLField(blank=True, null=True)),
                ('extra', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
