# Generated by Django 3.0.7 on 2020-06-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0007_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='extra_img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
