# Generated by Django 3.0.7 on 2020-06-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0010_skill_skillcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issued_by', models.CharField(blank=True, max_length=255, null=True)),
                ('issued_month', models.CharField(blank=True, max_length=20, null=True)),
                ('issued_year', models.CharField(blank=True, max_length=4, null=True)),
                ('validity', models.CharField(blank=True, max_length=10, null=True)),
                ('verification_id', models.CharField(blank=True, max_length=255, null=True)),
                ('verification_link', models.URLField(blank=True, null=True)),
                ('preview', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('email_alt', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('phone_alt', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'verbose_name': 'Skill Category', 'verbose_name_plural': 'Skill Categories'},
        ),
    ]
