# Generated by Django 3.0.7 on 2020-07-22 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0012_clientmails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientMails',
            new_name='ClientMail',
        ),
    ]
