# Generated by Django 3.0.7 on 2020-07-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0013_auto_20200723_0022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientmail',
            old_name='clientEmail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='clientmail',
            old_name='clientName',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='clientmail',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
