# Generated by Django 3.0.7 on 2020-07-30 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0015_auto_20200723_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Portfolio Category',
                'verbose_name_plural': 'Portfolio Categories',
            },
        ),
        migrations.CreateModel(
            name='PortfolioObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('preview', models.URLField()),
                ('highRes', models.URLField()),
                ('desc', models.TextField(blank=True, null=True)),
                ('workCredits', models.TextField(blank=True, null=True)),
                ('toolsUsed', models.TextField(blank=True, null=True)),
                ('externLink', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me.PortfolioCategory')),
            ],
        ),
    ]
